services:
  php:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: nefli
    
#  python:
#    build:
#      context: ./python
#      dockerfile: Dockerfile
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./python:/app
#    depends_on:
#      - mysql
#    environment:
#      MYSQL_HOST: mysql
#      MYSQL_USER: root
#      MYSQL_PASSWORD: password
#      MYSQL_DATABASE: productos

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: nefli
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql